### ISSUE TITLE
GLADE match failure on 2021oez

### ISSUE THREAD

**Issue by djones1040** [uiucsn/astro_ghost#25]
Hi Alex, had the GHOST Glade match find the wrong galaxy for SN 2021oez.  To reproduce::

  from astro_ghost.ghostHelperFunctions import getTransientHosts
  from astropy.coordinates import SkyCoord
  transient_position = SkyCoord(227.453641,0.533519,unit="deg")
  host_data = getTransientHosts(snCoord=[transient_position],transientName=['2021oez'],verbose=1,starcut="gentle")

**Comment by djones1040** [comment]
and then one (unrelated) weird failure in 2021pby (322.4025261,12.9163867), which appears to have a clear host in PS images (https://ps1images.stsci.edu/cgi-bin/ps1cutouts?pos=322.4025261226932%2B12.916386744605814&filter=color).  Thanks!  Sorry to bug you.

**Comment by alexandergagliano** [comment]
Hey @djones1040 Thanks for posting this issue! Could you let me know what version of GHOST you're running and what host you find for 2021oez? Running 2.0.17 on my end, I get the right host at `227.454941, 0.529834`. 

2021pby fails to find a match because the true host is dropped with bad photometry before the star/galaxy separation stage. Keeping in sources with bad photometry used to leave in more artifacts, but I've modified the code enough since then that I'll add them back in and run some tests. Removing this cut, the code finds the right host at `322.401673, 12.915681`.

**Comment by alexandergagliano** [comment]
Test transients get successfully matched, so I'll re-release with this fix tonight.

**Comment by alexandergagliano** [comment]
Released!

**Comment by djones1040** [comment]
thanks Alex, just tested and all good over here.  21pby looks good too.
